"Application As screen.'phoneLayout_FluidGridWithHeaderPageLayout_ver3.0'":
    OnVisible: =

    IBA_Logo As image:
        Height: =80
        Image: ='Institute_of_Business_Administration,_Karachi_(logo)'
        Width: =80
        X: =35
        Y: =40
        ZIndex: =3

    ProgressIndicator_3 As ProgressIndicator_2:
        applicationSteps: =collSteps
        Fill: =RGBA(255, 255, 255, 1)
        Y: =163
        ZIndex: =3

    LogoutButton As group:
        Height: =5
        Width: =5
        X: =60
        Y: =60
        ZIndex: =6

    PersonalSection As group:
        Height: =5
        Width: =5
        X: =60
        Y: =60
        ZIndex: =35

        PersonelDetailsLabel As label:
            Align: =Align.Center
            FontWeight: =FontWeight.Bold
            Height: =50
            Size: =20
            Text: ="Personal Details"
            Visible: =false
            Width: =245
            X: =194
            Y: =277
            ZIndex: =8

        NextButton As button:
            Fill: =RGBA(140, 4, 4, 1)
            FocusedBorderColor: =ColorFade(Self.Fill, -75%)
            Height: =63
            HoverBorderColor: =RGBA(238, 204, 204, 1)
            HoverFill: =ColorFade(RGBA(140.25, 4.090617, 4.090617, 1), -10%)
            OnSelect: =
            PressedBorderColor: =RGBA(203, 102, 102, 1)
            PressedColor: =RGBA(255, 255, 255, 1)
            PressedFill: =ColorFade(RGBA(203, 102, 102, 100), -10%)
            RadiusBottomLeft: =20
            RadiusBottomRight: =20
            RadiusTopLeft: =20
            RadiusTopRight: =20
            Text: ="Save and Continue"
            Visible: =false
            Width: =245
            X: =194
            Y: =1001
            ZIndex: =9

        FirstNameTF_1 As text:
            BorderColor: =RGBA(203, 102, 102, 1)
            Color: =RGBA(51, 51, 51, 1)
            Default: =""
            DisabledBorderColor: =RGBA(153, 153, 153, 1)
            DisplayMode: =DisplayMode.Disabled
            Fill: =RGBA(238, 204, 204, 1)
            Font: =Font.'Segoe UI'
            Height: =50
            HintText: ="First Name"
            HoverBorderColor: =ColorFade(RGBA(0, 120, 212, 1), -30%)
            HoverColor: =RGBA(51, 51, 51, 1)
            HoverFill: =RGBA(255, 255, 255, 1)
            PressedBorderColor: =RGBA(151, 0, 0, 1)
            PressedColor: =RGBA(0, 0, 0, 1)
            PressedFill: =RGBA(255, 255, 255, 1)
            RadiusBottomLeft: =10
            RadiusBottomRight: =10
            RadiusTopLeft: =10
            RadiusTopRight: =10
            Size: =15
            Visible: =false
            Width: =268
            X: =45
            Y: =358
            ZIndex: =10

        EmailTF_1 As text:
            BorderColor: =RGBA(203, 102, 102, 1)
            Default: =""
            DisplayMode: =DisplayMode.Disabled
            Fill: =RGBA(238, 204, 204, 1)
            Height: =51
            HintText: ="Email"
            PressedBorderColor: =RGBA(151, 0, 0, 1)
            RadiusBottomLeft: =10
            RadiusBottomRight: =10
            RadiusTopLeft: =10
            RadiusTopRight: =10
            Size: =15
            Visible: =false
            Width: =268
            X: =45
            Y: =442
            ZIndex: =11

        LastNameTF_1 As text:
            BorderColor: =RGBA(203, 102, 102, 1)
            Default: =""
            DisplayMode: =DisplayMode.Disabled
            Fill: =RGBA(238, 204, 204, 1)
            Height: =50
            HintText: ="Last Name"
            PressedBorderColor: =RGBA(151, 0, 0, 1)
            RadiusBottomLeft: =10
            RadiusBottomRight: =10
            RadiusTopLeft: =10
            RadiusTopRight: =10
            Size: =15
            Visible: =false
            Width: =268
            X: =330
            Y: =358
            ZIndex: =12

        PhoneNumberTxt_1 As text:
            BorderColor: =RGBA(203, 102, 102, 1)
            Default: =""
            DisplayMode: =DisplayMode.Disabled
            Fill: =RGBA(238, 204, 204, 1)
            Height: =51
            HintText: ="Phone Number"
            PressedBorderColor: =RGBA(151, 0, 0, 1)
            RadiusBottomLeft: =10
            RadiusBottomRight: =10
            RadiusTopLeft: =10
            RadiusTopRight: =10
            Size: =15
            Visible: =false
            Width: =268
            X: =330
            Y: =442
            ZIndex: =14

        TF As text:
            BorderColor: =RGBA(203, 102, 102, 1)
            Default: =""
            DisplayMode: =DisplayMode.Disabled
            Fill: =RGBA(238, 204, 204, 1)
            Height: =57
            HintText: ="CNIC/Passport"
            PressedBorderColor: =RGBA(151, 0, 0, 1)
            RadiusBottomLeft: =10
            RadiusBottomRight: =10
            RadiusTopLeft: =10
            RadiusTopRight: =10
            Size: =15
            Visible: =false
            Width: =268
            X: =43
            Y: =569
            ZIndex: =22

        Label As label:
            FontWeight: =FontWeight.Bold
            Height: =67
            Size: =15
            Text: ="CNIC/Passport Number"
            Visible: =false
            Width: =268
            X: =43
            Y: =510
            ZIndex: =23

        TF_1 As text:
            BorderColor: =RGBA(203, 102, 102, 1)
            Default: =""
            DisplayMode: =DisplayMode.Disabled
            Fill: =RGBA(238, 204, 204, 1)
            Height: =73
            HintText: ="Address"
            PressedBorderColor: =RGBA(151, 0, 0, 1)
            RadiusBottomLeft: =10
            RadiusBottomRight: =10
            RadiusTopLeft: =10
            RadiusTopRight: =10
            Size: =15
            Visible: =false
            Width: =552
            X: =46
            Y: =689
            ZIndex: =24

        Label_1 As label:
            FontWeight: =FontWeight.Bold
            Height: =67
            Size: =15
            Text: ="Address"
            Visible: =false
            Width: =268
            X: =43
            Y: =630
            ZIndex: =25

        TF_3 As text:
            BorderColor: =RGBA(203, 102, 102, 1)
            Default: =""
            DisplayMode: =DisplayMode.Disabled
            Fill: =RGBA(238, 204, 204, 1)
            Height: =57
            HintText: ="Address"
            PressedBorderColor: =RGBA(151, 0, 0, 1)
            RadiusBottomLeft: =10
            RadiusBottomRight: =10
            RadiusTopLeft: =10
            RadiusTopRight: =10
            Size: =15
            Visible: =false
            Width: =268
            X: =340
            Y: =825
            ZIndex: =28

        Label_3 As label:
            FontWeight: =FontWeight.Bold
            Height: =45
            Size: =15
            Text: ="Country"
            Visible: =false
            Width: =127
            X: =337
            Y: =782
            ZIndex: =29

        TF_4 As text:
            BorderColor: =RGBA(203, 102, 102, 1)
            Default: =""
            DisplayMode: =DisplayMode.Disabled
            Fill: =RGBA(238, 204, 204, 1)
            Height: =57
            HintText: ="Address"
            PressedBorderColor: =RGBA(151, 0, 0, 1)
            RadiusBottomLeft: =10
            RadiusBottomRight: =10
            RadiusTopLeft: =10
            RadiusTopRight: =10
            Size: =15
            Visible: =false
            Width: =260
            X: =43
            Y: =825
            ZIndex: =30

        Label_4 As label:
            FontWeight: =FontWeight.Bold
            Height: =45
            Size: =15
            Text: ="City"
            Visible: =false
            Width: =127
            X: =43
            Y: =782
            ZIndex: =31

        Label_2 As label:
            FontWeight: =FontWeight.Bold
            Height: =67
            Size: =15
            Text: ="Date of Birth"
            Visible: =false
            Width: =268
            X: =330
            Y: =515
            ZIndex: =33

        DatePicker1 As datepicker:
            BorderColor: =RGBA(140, 4, 4, 1)
            Color: =RGBA(128, 128, 128, 1)
            Height: =57
            IconBackground: |
                =RGBA(140, 4, 4, 1)
            Size: =24
            StartYear: =2000
            Visible: =false
            Width: =269
            X: =330
            Y: =577
            ZIndex: =34

    extracurricullarLabel As label:
        Align: =Align.Center
        FontWeight: =FontWeight.Bold
        Height: =34
        Size: =20
        Text: ="Extra Curricular"
        Width: =276
        X: =178
        Y: =270
        ZIndex: =51

    AcademicSection As group:
        Height: =5
        Width: =5
        X: =60
        Y: =60
        ZIndex: =51

        AcademicsLabel As label:
            Align: =Align.Center
            FontWeight: =FontWeight.Bold
            Height: =41
            Size: =20
            Text: ="Academics"
            Visible: =false
            Width: =216
            X: =208
            Y: =247
            ZIndex: =35

        AptitudeTestLabel As label:
            FontWeight: =FontWeight.Bold
            Height: =33
            Size: =15
            Text: ="Aptitude test"
            Visible: =false
            Width: =159
            X: =49
            Y: =315
            ZIndex: =36

        OlevelLabel As label:
            FontWeight: =FontWeight.Bold
            Height: =38
            Size: =15
            Text: ="Olevels / Matric"
            Visible: =false
            Width: =264
            X: =49
            Y: =510
            ZIndex: =37

        AlevelsLabel As label:
            FontWeight: =FontWeight.Bold
            Height: =33
            Size: =15
            Text: ="A-Levels / Inter"
            Visible: =false
            Width: =209
            X: =46
            Y: =709
            ZIndex: =38

        uploadLabel As label:
            Height: =55
            Size: =10
            Text: ="Please upload in *jpg, *png or *pdf files."
            Visible: =false
            Width: =223
            X: =376
            Y: =438
            ZIndex: =39

        eductionType1 As radio:
            Height: =99
            Items: =["O-levels","Matriculation"]
            RadioSize: =20
            Size: =21
            Visible: =false
            Width: =239
            X: =98
            Y: =571
            ZIndex: =40

        educationType2 As radio:
            Height: =99
            Items: =["A-levels","Intermediate"]
            RadioSize: =20
            Size: =21
            Visible: =false
            Width: =242
            X: =98
            Y: =764
            ZIndex: =41

        importSAT As import:
            Align: =Align.Right
            Fill: =RGBA(168, 0, 0, 1)
            Padding: =10
            Size: =18
            Text: ="Upload report"
            Visible: =false
            Width: =223
            X: =375
            Y: =398
            ZIndex: =42

        AptitudeTestLabel_6 As label:
            Height: =55
            Size: =15
            Text: ="Only SAT are accepted."
            Visible: =false
            Width: =240
            X: =115
            Y: =366
            ZIndex: =43

        Icon4 As icon.AddDocument:
            Color: =RGBA(255, 255, 255, 1)
            Fill: =RGBA(168, 0, 0, 1)
            Height: =38
            Icon: =Icon.AddDocument
            Visible: =false
            Width: =35
            X: =389
            Y: =398
            ZIndex: =44

        importEducation1 As import:
            Align: =Align.Right
            Fill: =RGBA(168, 0, 0, 1)
            Padding: =10
            Size: =18
            Text: ="Upload report"
            Visible: =false
            Width: =223
            X: =375
            Y: =574
            ZIndex: =45

        Icon4_2 As icon.AddDocument:
            Color: =RGBA(255, 255, 255, 1)
            Fill: =RGBA(168, 0, 0, 1)
            Height: =38
            Icon: =Icon.AddDocument
            Visible: =false
            Width: =35
            X: =389
            Y: =574
            ZIndex: =46

        importEducation2 As import:
            Align: =Align.Right
            Fill: =RGBA(168, 0, 0, 1)
            Padding: =10
            Size: =18
            Text: ="Upload report"
            Visible: =false
            Width: =223
            X: =376
            Y: =762
            ZIndex: =47

        Icon4_3 As icon.AddDocument:
            Color: =RGBA(255, 255, 255, 1)
            Fill: =RGBA(168, 0, 0, 1)
            Height: =38
            Icon: =Icon.AddDocument
            Visible: =false
            Width: =35
            X: =390
            Y: =762
            ZIndex: =48

        uploadLabel_1 As label:
            Height: =55
            Size: =10
            Text: ="Please upload in *jpg, *png or *pdf files."
            Visible: =false
            Width: =223
            X: =376
            Y: =618
            ZIndex: =49

        uploadLabel_2 As label:
            Height: =55
            Size: =10
            Text: ="Please upload in *jpg, *png or *pdf files."
            Visible: =false
            Width: =223
            X: =376
            Y: =802
            ZIndex: =50

    extracurricullarLabel_1 As label:
        FontWeight: =FontWeight.Bold
        Height: =33
        Size: =18
        Text: ="Hobbies"
        Width: =221
        X: =78
        Y: =318
        ZIndex: =52

    hobbyTF As text:
        Default: =""
        Height: =157
        HintText: ="My hobbies"
        Mode: =TextMode.MultiLine
        Size: =15
        Width: =495
        X: =78
        Y: =358
        ZIndex: =53

    extracurricullarLabel_2 As label:
        FontWeight: =FontWeight.Bold
        Height: =33
        Size: =18
        Text: ="Sports"
        Width: =221
        X: =78
        Y: =545
        ZIndex: =54

    sportTF As text:
        Default: =""
        Height: =157
        HintText: ="My Sport acheivements"
        Mode: =TextMode.MultiLine
        Size: =15
        Width: =495
        X: =78
        Y: =585
        ZIndex: =55

    extracurricullarLabel_3 As label:
        FontWeight: =FontWeight.Bold
        Height: =33
        Size: =18
        Text: ="Others"
        Width: =221
        X: =78
        Y: =764
        ZIndex: =56

    sportTF_1 As text:
        Default: =""
        Height: =157
        HintText: ="Other acheivements"
        Mode: =TextMode.MultiLine
        Size: =15
        Width: =495
        X: =78
        Y: =804
        ZIndex: =57

    NextBtn_1 As button:
        Fill: =RGBA(140, 4, 4, 1)
        FocusedBorderColor: =ColorFade(Self.Fill, -75%)
        Height: =60
        HoverBorderColor: =RGBA(238, 204, 204, 1)
        HoverFill: =ColorFade(RGBA(140.25, 4.090617, 4.090617, 1), -10%)
        OnSelect: =
        PressedBorderColor: =RGBA(203, 102, 102, 1)
        PressedColor: =RGBA(255, 255, 255, 1)
        PressedFill: =ColorFade(RGBA(203, 102, 102, 100), -10%)
        RadiusBottomLeft: =20
        RadiusBottomRight: =20
        RadiusTopLeft: =20
        RadiusTopRight: =20
        Text: ="Next"
        Width: =175
        X: =400
        Y: =1004
        ZIndex: =58

    NextBtn_2 As button:
        Fill: =RGBA(140, 4, 4, 1)
        FocusedBorderColor: =ColorFade(Self.Fill, -75%)
        Height: =60
        HoverBorderColor: =RGBA(238, 204, 204, 1)
        HoverFill: =ColorFade(RGBA(140.25, 4.090617, 4.090617, 1), -10%)
        OnSelect: =
        PressedBorderColor: =RGBA(203, 102, 102, 1)
        PressedColor: =RGBA(255, 255, 255, 1)
        PressedFill: =ColorFade(RGBA(203, 102, 102, 100), -10%)
        RadiusBottomLeft: =20
        RadiusBottomRight: =20
        RadiusTopLeft: =20
        RadiusTopRight: =20
        Text: ="Previous"
        Width: =175
        X: =78
        Y: =1004
        ZIndex: =59

