"Application As screen.'phoneLayout_FluidGridWithHeaderPageLayout_ver3.0'":
    OnVisible: =

    Label3 As label:
        BorderColor: =RGBA(151, 0, 0, 1)
        Color: =RGBA(140, 4, 4, 1)
        FontWeight: =FontWeight.Bold
        Height: =70
        Size: =21
        Text: =ProgressIndicator_3.selectedStep
        Width: =560
        X: =45
        Y: =304
        ZIndex: =2

    logo_1 As image:
        Height: =80
        Image: ='Institute_of_Business_Administration,_Karachi_(logo)'
        Width: =80
        X: =35
        Y: =40
        ZIndex: =3

    ProgressIndicator_3 As ProgressIndicator_2:
        applicationSteps: =collSteps
        Fill: =RGBA(255, 255, 255, 1)
        Y: =163
        ZIndex: =3

    Logout_1 As group:
        Height: =5
        Width: =5
        X: =60
        Y: =60
        ZIndex: =6

        Icon8_1 As icon.Leave:
            Color: =RGBA(118, 0, 0, 1)
            FocusedBorderThickness: =0
            Height: =40
            Icon: =Icon.Leave
            OnSelect: |-
                =Navigate('Login Screen',ScreenTransition.Fade);
                Clear(User);
            Width: =30
            X: =555
            Y: =54
            ZIndex: =4

        Status_2 As label:
            Color: =RGBA(118, 0, 0, 1)
            FontWeight: =FontWeight.Semibold
            Height: =30
            OnSelect: |-
                =Navigate('Login Screen',ScreenTransition.Fade);
                Clear(User);
            Size: =15
            Text: ="Logout"
            Width: =94
            X: =531
            Y: =94
            ZIndex: =6

    "'Register Label_1' As label":
        Align: =Align.Center
        FontWeight: =FontWeight.Bold
        Height: =50
        Size: =20
        Text: ="Personal Details"
        Width: =245
        X: =192
        Y: =259
        ZIndex: =8

    RegisterBtn_1 As button:
        Fill: =RGBA(140, 4, 4, 1)
        FocusedBorderColor: =ColorFade(Self.Fill, -75%)
        Height: =48
        HoverBorderColor: =RGBA(238, 204, 204, 1)
        HoverFill: =ColorFade(RGBA(140.25, 4.090617, 4.090617, 1), -10%)
        OnSelect: =
        PressedBorderColor: =RGBA(203, 102, 102, 1)
        PressedColor: =RGBA(255, 255, 255, 1)
        PressedFill: =ColorFade(RGBA(203, 102, 102, 100), -10%)
        RadiusBottomLeft: =20
        RadiusBottomRight: =20
        RadiusTopLeft: =20
        RadiusTopRight: =20
        Text: ="Register"
        Width: =174
        X: =233
        Y: =945
        ZIndex: =9

    FirstNameTF_1 As text:
        BorderColor: =RGBA(203, 102, 102, 1)
        Color: =RGBA(51, 51, 51, 1)
        Default: =""
        DisabledBorderColor: =RGBA(153, 153, 153, 1)
        DisplayMode: =DisplayMode.Disabled
        Fill: =RGBA(238, 204, 204, 1)
        Font: =Font.'Segoe UI'
        Height: =50
        HintText: ="First Name"
        HoverBorderColor: =ColorFade(RGBA(0, 120, 212, 1), -30%)
        HoverColor: =RGBA(51, 51, 51, 1)
        HoverFill: =RGBA(255, 255, 255, 1)
        PressedBorderColor: =RGBA(151, 0, 0, 1)
        PressedColor: =RGBA(0, 0, 0, 1)
        PressedFill: =RGBA(255, 255, 255, 1)
        RadiusBottomLeft: =10
        RadiusBottomRight: =10
        RadiusTopLeft: =10
        RadiusTopRight: =10
        Size: =15
        Width: =268
        X: =43
        Y: =340
        ZIndex: =10

    EmailTF_1 As text:
        BorderColor: =RGBA(203, 102, 102, 1)
        Default: =""
        DisplayMode: =DisplayMode.Disabled
        Fill: =RGBA(238, 204, 204, 1)
        Height: =51
        HintText: ="Email"
        PressedBorderColor: =RGBA(151, 0, 0, 1)
        RadiusBottomLeft: =10
        RadiusBottomRight: =10
        RadiusTopLeft: =10
        RadiusTopRight: =10
        Size: =15
        Width: =268
        X: =43
        Y: =424
        ZIndex: =11

    LastNameTF_1 As text:
        BorderColor: =RGBA(203, 102, 102, 1)
        Default: =""
        DisplayMode: =DisplayMode.Disabled
        Fill: =RGBA(238, 204, 204, 1)
        Height: =50
        HintText: ="Last Name"
        PressedBorderColor: =RGBA(151, 0, 0, 1)
        RadiusBottomLeft: =10
        RadiusBottomRight: =10
        RadiusTopLeft: =10
        RadiusTopRight: =10
        Size: =15
        Width: =268
        X: =328
        Y: =340
        ZIndex: =12

    PhoneNumberTF_1 As text:
        BorderColor: =RGBA(203, 102, 102, 1)
        Default: =""
        Fill: =RGBA(238, 204, 204, 1)
        Height: =51
        HintText: ="Phone Number"
        PressedBorderColor: =RGBA(151, 0, 0, 1)
        RadiusBottomLeft: =10
        RadiusBottomRight: =10
        RadiusTopLeft: =10
        RadiusTopRight: =10
        Size: =15
        Width: =268
        X: =328
        Y: =424
        ZIndex: =13

    PhoneNumberTxt_1 As text:
        BorderColor: =RGBA(203, 102, 102, 1)
        Default: =""
        DisplayMode: =DisplayMode.Disabled
        Fill: =RGBA(238, 204, 204, 1)
        Height: =51
        HintText: ="Phone Number"
        PressedBorderColor: =RGBA(151, 0, 0, 1)
        RadiusBottomLeft: =10
        RadiusBottomRight: =10
        RadiusTopLeft: =10
        RadiusTopRight: =10
        Size: =15
        Width: =268
        X: =328
        Y: =424
        ZIndex: =14

    ProgramsDropDown_1 As dropdown:
        BorderColor: =RGBA(203, 102, 102, 1)
        ChevronBackground: =RGBA(255, 255, 255, 1)
        ChevronFill: =RGBA(0, 0, 0, 1)
        ChevronHoverBackground: |
            =ColorFade(Self.BorderColor, 15%)
        Default: ="CNIC"
        Fill: =RGBA(238, 204, 204, 1)
        Height: =49
        HoverFill: =RGBA(203, 102, 102, 1)
        Items: =["BBA","BSCS","BSACF","BSEM","BSSS","BSECO"]
        PressedFill: =RGBA(151, 0, 0, 1)
        SelectionFill: =RGBA(220, 153, 153, 1)
        Size: =15
        Width: =268
        X: =35
        Y: =1087
        ZIndex: =20

    ProgramsInterestedIn_1 As label:
        FontWeight: =FontWeight.Bold
        Height: =39
        Size: =15
        Text: ="Programs Interested In?"
        Width: =560
        X: =35
        Y: =1050
        ZIndex: =21

    TF As text:
        BorderColor: =RGBA(203, 102, 102, 1)
        Default: =""
        DisplayMode: =DisplayMode.Disabled
        Fill: =RGBA(238, 204, 204, 1)
        Height: =57
        HintText: ="CNIC/Passport"
        PressedBorderColor: =RGBA(151, 0, 0, 1)
        RadiusBottomLeft: =10
        RadiusBottomRight: =10
        RadiusTopLeft: =10
        RadiusTopRight: =10
        Size: =15
        Width: =268
        X: =41
        Y: =551
        ZIndex: =22

    Label As label:
        FontWeight: =FontWeight.Bold
        Height: =67
        Size: =15
        Text: ="CNIC/Passport Number"
        Width: =268
        X: =41
        Y: =492
        ZIndex: =23

    TF_1 As text:
        BorderColor: =RGBA(203, 102, 102, 1)
        Default: =""
        DisplayMode: =DisplayMode.Disabled
        Fill: =RGBA(238, 204, 204, 1)
        Height: =73
        HintText: ="Address"
        PressedBorderColor: =RGBA(151, 0, 0, 1)
        RadiusBottomLeft: =10
        RadiusBottomRight: =10
        RadiusTopLeft: =10
        RadiusTopRight: =10
        Size: =15
        Width: =552
        X: =44
        Y: =671
        ZIndex: =24

    Label_1 As label:
        FontWeight: =FontWeight.Bold
        Height: =67
        Size: =15
        Text: ="Address"
        Width: =268
        X: =41
        Y: =612
        ZIndex: =25

    TF_3 As text:
        BorderColor: =RGBA(203, 102, 102, 1)
        Default: =""
        DisplayMode: =DisplayMode.Disabled
        Fill: =RGBA(238, 204, 204, 1)
        Height: =57
        HintText: ="Address"
        PressedBorderColor: =RGBA(151, 0, 0, 1)
        RadiusBottomLeft: =10
        RadiusBottomRight: =10
        RadiusTopLeft: =10
        RadiusTopRight: =10
        Size: =15
        Width: =268
        X: =338
        Y: =807
        ZIndex: =28

    Label_3 As label:
        FontWeight: =FontWeight.Bold
        Height: =45
        Size: =15
        Text: ="Country"
        Width: =127
        X: =335
        Y: =764
        ZIndex: =29

    TF_4 As text:
        BorderColor: =RGBA(203, 102, 102, 1)
        Default: =""
        DisplayMode: =DisplayMode.Disabled
        Fill: =RGBA(238, 204, 204, 1)
        Height: =57
        HintText: ="Address"
        PressedBorderColor: =RGBA(151, 0, 0, 1)
        RadiusBottomLeft: =10
        RadiusBottomRight: =10
        RadiusTopLeft: =10
        RadiusTopRight: =10
        Size: =15
        Width: =260
        X: =41
        Y: =807
        ZIndex: =30

    Label_4 As label:
        FontWeight: =FontWeight.Bold
        Height: =45
        Size: =15
        Text: ="City"
        Width: =127
        X: =41
        Y: =764
        ZIndex: =31

